all:
	gcc -o portsscan/portsscan portsscan/portsscan.c
	mkdir -p network_monitor/out/tcpdump
	mkdir -p network_monitor/out/tcpflow
	chmod u+x checkfile/checkfile.py
	chmod u+x honeypot/honeypot.py
	chmod u+x network_monitor/mongo_connect.py
	chmod u+x network_monitor/process_tcpdump.py
	chmod u+x network_monitor/process_tcpflow.py
	chmod u+x CTF-ExploitLauncher/Exploit_Launcher.py
